- hosts: localhost
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Creating EC2
    ec2: 
      key_name: master_key
      instance_type: t2.micro
      image: ami-0f5ee92e2d63afc18
      region: "ap-south-1"
      count: 1
      vpc_subnet_id: vpc-06328180e2f3e16e5
      assign_public_ip: yes
