---
 - hosts: all
   become: yes
   vars_files: valut_pass.yaml
    tasks:
      - name: trying out echo command
         ansible.builtin.debug:
          msg: "helo my username is {{username}} & pass is {{password}}"
